RunSP/Controllers/FormRunSpController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Configuration;
using System.Web.Security;
using System.Data.SqlClient;
using RunSP.Models;

namespace RunSP.Controllers
{
    public class FormRunSpController : Controller
    {

                         
        //
        // GET: /FormRunSp/
        public ActionResult Index(Barang model)
        {
            //buttonclick();
            if (!String.IsNullOrEmpty(model.btnsubmit))
            {
                Dataset ds = new Dataset();
                SqlConnection conn;
                SqlCommand cmd = new SqlCommand();

                SqlParameter sp1 = new SqlParameter();
                SqlParameter sp2 = new SqlParameter();

                conn = new SqlConnection("server=10.10.10.26:database=DbTest;uid=sa;pwd=Haan@Colatta138");
                cmd.Parameters.Add("@nama", sqlDbType.Varchar).Value = fromdate.text;
                cmd.Parameters.Add("@jenis", sqlDbType.Varchar).Value = todate.text;
                cmd = new SqlCommand("submitrecord", conn);
                cmd.CommandType = CommandType.StoredProcedure;
                conn.Open();
                cmd.ExecuteNonQuery();
                conn.Close();
            }
            return View();
        }

        protected void buttonclick(object sender, EventArgs e)
        {
           /* Dataset ds = new Dataset();
            SqlConnection conn;
            SqlCommand cmd = new SqlCommand();

            SqlParameter sp1 = new SqlParameter();
            SqlParameter sp2 = new SqlParameter();

            conn = new SqlConnection("server=10.10.10.26:database=DbTest;uid=sa;pwd=Haan@Colatta138");
            cmd.Parameters.Add("@nama", sqlDbType.Varchar).Value = fromdate.text;
            cmd.Parameters.Add("@jenis", sqlDbType.Varchar).Value = todate.text;
            cmd = new SqlCommand("submitrecord", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();*/
        }

        public ActionResult Welcome(string name, int numTimes = 1)
        {
            ViewBag.Message = "Hello " + name;
            ViewBag.NumTimes = numTimes;

            return View();
        }

	}
}

RunSP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Run Stored Procedure</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Run Stored Procedure", "Index", "FormRunSp", null, new { @class = "navbar-brand" })
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>